### ISSUE TITLE
Entity extraction using ruta scripts are not working post upgrading uima and ruta to 3x version.

### ISSUE THREAD

**Issue by raghu298** [apache/uima-ruta#129]
Entity extraction using ruta scripts are not working post upgrading uima and ruta to 3x version.
It was working fine with 2x versions and only JCas classes are upgraded to 3x version.
I did not find any exceptions but its not detecting any entities.

Any extra steps need to do for ruta scripts during migration.

versions used:
[uimaj-3.4.1]
[uimafit-3.4.0]
[ruta-3.3.0]
[cleartk-3.0.0]

i am expecting any heads up which can help in debugging this and any steps that missed during migration.

**Comment by reckart** [comment]
Have you tried running your scripts using the Ruta Eclipse plugins in Ruta debug mode?

**Comment by raghu298** [comment]
yes , its working with ruta eclipse plugin and tested with below eclipse update
https://downloads.apache.org/uima/eclipse-update-site-v3/

**Comment by raghu298** [comment]
Getting Null pointer exception from the framework side

at org.apache.uima.ruta.condition.PartOfCondition.check(PartOfCondition.java:80) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.condition.PartOfCondition.eval(PartOfCondition.java:52) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.condition.NotCondition.eval(NotCondition.java:37) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.condition.AndCondition.eval(AndCondition.java:42) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.rule.RutaRuleElement.doMatch(RutaRuleElement.java:381) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.rule.RutaRuleElement.startMatch(RutaRuleElement.java:81) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.rule.ComposedRuleElement.startMatch(ComposedRuleElement.java:79) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.rule.RutaRule.apply(RutaRule.java:72) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.rule.RutaRule.apply(RutaRule.java:63) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.rule.RutaRule.apply(RutaRule.java:42) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.block.RutaScriptBlock.apply(RutaScriptBlock.java:74) ~[ruta-core-3.3.0.jar:?] 
	at org.apache.uima.ruta.RutaModule.apply(RutaModule.java:56) ~[ruta-core-3.3.0.jar:?]

**Comment by reckart** [comment]
I dimly remember something about potentially having to re-generate ruta basic annotations in particular after certain actions such as deleting annotations or adding annotations outside of ruta scripts. Check the `RutaEngine.PARAM_REINDEX_UPDATE_MODE`, e.g. try setting it to `COMPLETE`.

**Comment by raghu298** [comment]
Its not helping and mostly anchors values are coming as null in ruta internal classes

**Comment by reckart** [comment]
@pkluegl Any idea?

**Comment by raghu298** [comment]
@reckart:

The RutaBasic annotations store additional information about the annotations. 
They need to be updated for each addition or removal of any annotations, 
i.e internal maps need to be up to date all the time or else the rules will be executed incorrectly. 
The RutaBasic annotations can be shared across different analysis engines processing the same CAS and the RutaEngine provides parameters configuring the internal update strategy. 
These parameters are named PARAM_INDEX_** or PARAM_REINDEX_**.

If runtime is not an issue, then you can set PARAM_REINDEX_UPDATE_MODE to COMPLETE and the RutaEngine will update everything.

These configuration helped and it regenerated ruta basic annotations.

**Comment by reckart** [comment]
Thanks for the feedback!
