### ISSUE TITLE
Unable to use Ruta Query view in Ruta 3.4.0-RC-1

### ISSUE THREAD

**Issue by reckart** [apache/uima-ruta#151]
**Describe the bug**
When trying to use the Ruta query view in Eclipse, an exception is generated.

**To Reproduce**
1. Install Ruta 3.4.0 RC 1
2. Switch to Ruta perspective
3. Locate the query view in the middle lower part of the screen
4. Choose an XMI file in the "Query data" input field
5. Choose a typesystem as well
6. Press the green "play" button.

**Expected behavior**
Some kind of result - no error.

**Screenshots**
```
java.lang.NoClassDefFoundError: org/apache/uima/ruta/ReindexUpdateMode
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at org.apache.uima.fit.internal.ReflectionUtil.getFields(ReflectionUtil.java:59)
	at org.apache.uima.fit.internal.ReflectionUtil.getFields(ReflectionUtil.java:45)
	at org.apache.uima.fit.component.initialize.ConfigurationParameterInitializer.initialize(ConfigurationParameterInitializer.java:101)
	at org.apache.uima.fit.component.JCasAnnotator_ImplBase.initialize(JCasAnnotator_ImplBase.java:35)
	at org.apache.uima.ruta.engine.RutaEngine.initialize(RutaEngine.java:639)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.lambda$callInitializeMethod$2(AnalysisEngineImplBase.java:658)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.withContexts(AnalysisEngineImplBase.java:698)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.callInitializeMethod(AnalysisEngineImplBase.java:658)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:243)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:167)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:97)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:64)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:284)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:334)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:449)
	at org.apache.uima.ruta.query.ui.QueryActionHandler$QueryHandlerJob.run(QueryActionHandler.java:193)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.apache.uima.ruta.ReindexUpdateMode cannot be found by org.apache.uima.ruta.engine_3.4.0
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:487)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 20 more
```

**Please complete the following information:**
 - Version: 3.4.0-RC-1

**Comment by reckart** [comment]
* Install plugins into Eclipse IDE for Eclipse Committers
* Open Host OSGi Console in Console view
* Check who requires the org.apache.uima.ruta bundle and who provides it: `inspect req osgi.wiring.package`
   ```
   osgi.wiring.package; (&(osgi.wiring.package=org.apache.uima.ruta)(&(version>=3.4.0)(!(version>=4.0.0)))) resolved by:
   osgi.wiring.package; org.apache.uima.ruta 3.4.0 from org.apache.uima.ruta.core.ext_3.4.0 [582]
   ```
* Check exported packages of `org.apache.uima.ruta.core.ext_3.4.0 [582]`: `headers 582`
  ```
  headers 582
  
  Bundle headers:
     ...
     Export-Package = org.apache.uima.ruta;version="3.4.0"
     ...
  ```
* Check what is the ID of `org.apache.uima.ruta.engine_3.4.0` (`ss`) and then what its header are: `headers 583`
  ```
  headers 583

   Bundle headers:
      ...
      Export-Package = org.apache.uima.ruta;version="3.4.0",...
      ...
  ```

Looks like we have two bundles exporting the `org.apache.uima.ruta` package and the "wrong" one is wired so the class we are looking for cannot be found.
